{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.data_text|compare('1')}
    {'No expiration date'|i18n( 'extension/xrowimagelicensing/datatypes' )}
{elseif $attribute.data_text|compare('0')}
    {if $attribute.content.is_valid}
        {'Delete on'|i18n( 'extension/xrowimagelicensing/datatypes' )}: {$attribute.content.timestamp|l10n(shortdatetime)}
    {/if}
{/if}